## 등굣길

In [21]:
import numpy as np

def solution(m, n, puddles):
    board = np.ones((n, m))
    for item in puddles:
        board[item[1]-1][item[0]-1] = 0
    for row in range(1, n):
        if board[row][0] != 0:
            board[row][0] = board[row - 1][0] % 1000000007
    for col in range(1, m):
        if board[0][col] != 0:
            board[0][col] = board[0][col - 1] % 1000000007
    
    for row in range(1, n):
        for col in range(1, m):
            if board[row][col] != 0:
                board[row][col] = board[row-1][col] + board[row][col-1] % 1000000007

    return int(board[n-1][m-1]) % 1000000007

In [22]:
m = 4
n = 3
puddles = [[2, 2]]

solution(m, n, puddles)

[[1. 1. 1. 1.]
 [1. 0. 1. 2.]
 [1. 1. 2. 0.]]


0