## 크레인 인형뽑기

### map, zip 을 통한 transpose, 리스트 컴프리헨션 사용

In [86]:
board = [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]
moves = [1,5,3,5,1,2,1,4]
# result will be 4

In [79]:
print(np.array(board))

[[0 0 0 0 0]
 [0 0 1 0 3]
 [0 2 5 0 1]
 [0 2 4 4 2]
 [0 5 1 3 1]]


In [25]:
import numpy as np

print(np.array(board).T)

[[0 0 0 4 3]
 [0 0 2 2 5]
 [0 1 5 4 1]
 [0 0 0 4 3]
 [0 3 1 2 1]]


In [45]:
board[2].remove(0)
print(board)

[[0, 0, 0, 0, 0], [0, 0, 1, 0, 3], [2, 5, 0, 1], [4, 2, 4, 4, 2], [3, 5, 1, 3, 1]]


In [52]:
import numpy as np

a = np.array(board).T
a[2][2] = 0
print(a)

[[0 0 0 4 3]
 [0 0 2 2 5]
 [0 1 0 4 1]
 [0 0 0 4 3]
 [0 3 1 2 1]]


In [84]:
c = list(map(list, zip(*board)))
print(c)
plz = []
for row in c:
    row = [item for item in row if item != 0]
    row.reverse()
    plz.append(row)

print(plz)

[[0, 0, 0, 0, 0], [0, 0, 2, 2, 5], [0, 1, 5, 4, 1], [0, 0, 0, 4, 3], [0, 3, 1, 2, 1]]
[[], [5, 2, 2], [1, 4, 5, 1], [3, 4], [1, 2, 1, 3]]


In [72]:
a = [1, 2, 3]

print(len(a))

3


In [87]:
## 제출

refined = []
bascket = [0]
answer = 0

for row in list(map(list, zip(*board))):
    row = [item for item in row if item != 0]
    row.reverse()
    refined.append(row)
    
for crane in moves:
    if len(refined[crane-1]) > 0:
        bascket.append(refined[crane-1].pop())
        if bascket[-1] == bascket[-2]:
            bascket.pop()
            bascket.pop()
            answer += 2
        
print(bascket)
print(answer)

[0, 4, 2, 4]
4
