In [19]:
key = [[0, 0, 0], [1, 0, 0]]

import numpy as np

np_key = np.array(key)



In [20]:
lock = [[1, 1, 1], [1, 1, 0], [1, 0, 1]]

np_key, np_lock = np.array(key), np.array(lock)

print(np_key)
print(np_lock)

[[0 0 0]
 [1 0 0]]
[[1 1 1]
 [1 1 0]
 [1 0 1]]


In [21]:
kk = np.c_[np_key, [0,0]]
print(kk)
kk = np.r_[kk, [0, 0, 0, 0]]

print(kk)

[[0 0 0 0]
 [1 0 0 0]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [6]:
print(len(np_lock))

3
